# JWT_SECRET=7[:l9@8F_48+,2B}V7lmb0GwYQgMU.7kl

version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo_backend
    ports:
      - '3000:3000'
    # La correction la plus importante est ici.
    # On dit à Docker de synchroniser le code, mais de BIEN garder
    # le node_modules qui a été créé pendant le build.
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    # On passe en mode développement pour le hot-reload
    command: npm run start:dev
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=tododb
      # - JWT_SECRET=TA_CLE_SECRETE_ULTRA_COMPLIQUEE_ET_TRES_LONGUE
      - JWT_SECRET=7[:l9@8F_48+,2B}V7lmb0GwYQgMU.7kl

  frontend:
    build:
      # On pointe vers le nouveau dossier 'todolist'
      context: ./frontend/todolist
      dockerfile: Dockerfile
    container_name: todo_frontend
    ports:
      - "5173:5173"
    volumes:
      # On pointe vers le nouveau dossier 'todolist'
      - ./frontend/todolist:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: todo_db
    restart: always
    environment:
      MYSQL_DATABASE: tododb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: